language: node_js
sudo: false
node_js:
  - "4.2"
addons:
  postgresql: "9.4"
services:
  - postgresql
  - redis-server
before_script:
  - createuser astral-test
  - createdb astral-test
  - npm run migrate-test
script:
  - npm test
